name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  macos:
    name: macOS
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: make test-swift

  ubuntu:
    strategy:
      matrix:
        swift:
          - '6.2'

    container: swift:${{ matrix.swift }}
    name: Linux (Swift ${{ matrix.swift }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: swift test

  android:
    strategy:
      matrix:
        swift:
          - "6.2"
    name: Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: skiptools/swift-android-action@v2
        with:
          swift-version: ${{ matrix.swift }}
          copy-files: ${GITHUB_WORKSPACE}/Tests/SnapshotTestingTests/__Snapshots__
